# Generated by Django 5.2.12 on 2026-03-06 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
