# Generated by Django 5.1.7 on 2026-03-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_supportmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
